const categories = [
    {"name": "Demos",       "description": "These demonstrations are intended to illustrate a concept or idea. Many stemmed from either an idea for a blog post, or from coding interview questions."},
    {"name": "Games",       "description": ""},
    {"name": "Utilities",   "description": ""},
    {"name": "Toys",        "description": "These are simple apps that are meant to be interesting, but serve no real purpose. Pretty much the fidget spinners of apps on this website."},
    {"name": "NYT Helpers", "description": "These utilities are helpful for solving the NYT word games."},
    {"name": "Medical",     "description": "These apps were produced because of my interest in human biology. However these apps should not be used for medical diagnosis. They are for interest and novelty use only."},
    {"name": "Ideas",       "description": "These are unproduced ideas. As I have time, I may augment these into fully functional apps."},
];

const flairs = {
    "ALPHA":   "crimson",
    "BETA":    "steelblue",
    "UPDATED": "green",
    "NEW":     "green",
};

const apps = [
    {
        "name"          : "2-XL Simulator",
        "location"      : "2xl",
        "category"      : "Toys",
        "icon"          : "icon_2xl",
        "status"        : true,
        "description"   : "2-XL Toy Simulator",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "3-Tris",
        "location"      : "tetriscubed",
        "category"      : "Games",
        "icon"          : "icon_3tris",
        "visible"       : true,
        "description"   : "Top-down 3D Tetris-style game. It's very much inspired by the old Macintosh game 3Tris/3Wiz!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "8-Ball",
        "location"      : "8ball/",
        "category"      : "Toys",
        "icon"          : "icon_8ball",
        "visible"       : true,
        "description"   : "Eons ago, I made a digital Magic 8-Ball using Bryce, Photoshop, and Illustrator, then made it work using server-side include commands. This is a re-implementation using SVG and Javascript.",
        "date"          : "Unknown",
        "flair"         : null,
        "tags"          : [],
        "mobile"        : true,
    },
    {
        "name"          : "Barcode Generator",
        "location"      : "barcode",
        "category"      : "Utilities",
        "icon"          : "icon_barcode",
        "visible"       : true,
        "description"   : "A simple barcode 128 generator using Javascript and an HTML canvas.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Bayes",
        "location"      : "bayes",
        "category"      : "Demos",
        "icon"          : "icon_bayes",
        "visible"       : true,
        "description"   : "Interactive bayes demonstration for understanding statistical test results.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Bezier",
        "location"      : "bezier",
        "category"      : "Demos",
        "icon"          : "icon_bezier",
        "visible"       : true,
        "description"   : "Bezier Curve Demo that visually shows how b&eacute; curves are constructed.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Boing",
        "location"      : "boing/",
        "category"      : "Toys",
        "icon"          : "icon_boing",
        "visible"       : true,
        "description"   : "A reimagining of the classic Amiga Boing demo app using SVG. The rotation is done by color cycling just like the original.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "BoogieBoardy",
        "location"      : "boogie",
        "category"      : "Toys",
        "icon"          : "icon_boogie",
        "visible"       : true,
        "description"   : "Basic drawing for kids, just like a real Boogie Board",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "CandyRain",
        "location"      : "candyrain",
        "category"      : "Games",
        "icon"          : "icon_candyrain",
        "visible"       : true,
        "description"   : "Good and Plenties are so good they deserve their own game!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Cheatle",
        "location"      : "cheatle",
        "category"      : "NYT Helpers",
        "icon"          : "icon_cheatle",
        "visible"       : true,
        "description"   : "Tired of not winning at Wordle? Use Cheatle to help suss out the words you just can't get.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Circle Illusion",
        "location"      : "circle",
        "category"      : "Toys",
        "icon"          : "icon_circle",
        "visible"       : true,
        "description"   : "The appearance of a circle generated with only linear motion",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Codey",
        "location"      : "codey/",
        "category"      : "Games",
        "icon"          : "icon_codey",
        "visible"       : true,
        "description"   : "Guess the color code within 10 guesses to win!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Cone Test",
        "location"      : "medical/cone.html",
        "category"      : "Medical",
        "icon"          : "icon_conetest",
        "visible"       : true,
        "description"   : "Eye test that checks for cone sensitivity to red, green, and blue wavelengths. Novelty use only, not to be used as a diagnosis tool.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Day Calculator",
        "location"      : "date",
        "category"      : "Demos",
        "icon"          : "icon_date",
        "visible"       : true,
        "description"   : "Calculate the day of the week for any date using Lewis Carrol's method.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Dots",
        "location"      : "dots",
        "category"      : "Games",
        "icon"          : "icon_dots",
        "visible"       : true,
        "description"   : "The classic game of making squares from dots",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "DTMF Simulator",
        "location"      : "dtmf",
        "category"      : "Toys",
        "icon"          : "icon_dtmf",
        "visible"       : true,
        "description"   : "Generate dual tone signals like the good old days",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "DVD Screensaver",
        "location"      : "dvd",
        "category"      : "Toys",
        "icon"          : "icon_dvd",
        "visible"       : true,
        "description"   : "A reimagining of the classic DVD screensaver",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Dicey",
        "location"      : "dicey",
        "category"      : "Games",
        "icon"          : "icon_dicey",
        "visible"       : true,
        "description"   : "Dicey is a familiar dice game where you score points by rolling various combinations using 5 dice.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Dionakra",
        "location"      : "dionakra",
        "category"      : "Games",
        "icon"          : "icon_dionakra",
        "visible"       : true,
        "description"   : "This is a basic breakout clone.",
        "date"          : "11/30/2025",
        "tags"          : [],
        "flair"         : "BETA",
        "mobile"        : true,
    },
    {
        "name"          : "Fling Solver",
        "location"      : "fling/",
        "category"      : "Utilities",
        "icon"          : "icon_fling",
        "visible"       : true,
        "description"   : "Tool to help find solutions to the iPhone game called Fling",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Game Of Life",
        "location"      : "life",
        "category"      : "Toys",
        "icon"          : "icon_gol",
        "visible"       : true,
        "description"   : "Conway's classic game of life built using Javascript and HTML5 canvas.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Groups",
        "location"      : "groups",
        "category"      : "Games",
        "icon"          : "icon_groups",
        "visible"       : true,
        "description"   : "Find groups of 3 cards whose characterstics are either all the same, or all different. The game ends when all the cards are gone.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Hearing Test",
        "location"      : "medical/hearing.html",
        "category"      : "Medical",
        "icon"          : "icon_hearing",
        "visible"       : true,
        "description"   : "Hearing test is a pure tone audiometry test designed to map the sensitivity to frequencies in the normal range of hearing. Novelty use only, not to be used as a diagnosis tool.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Hopeless",
        "location"      : "hopeless",
        "category"      : "Games",
        "icon"          : "icon_hopeless",
        "visible"       : true,
        "description"   : "A puzzle game where you try remove all the blocks by clicking on groups of more than 2. This was an exercize in getting familiar with the canvas.",
        "date"          : "Unknown",
        "tags"          : ["Updated"],
        "flair"         : "UPDATED",
        "mobile"        : false,
    },
    {
        "name"          : "Hue're Adorable",
        "location"      : "huey/",
        "category"      : "Games",
        "icon"          : "icon_hue",
        "visible"       : true,
        "description"   : "A simple game where you reconstruct a gradient that's been split into pieces and shuffled.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Ishihara Test",
        "location"      : "medical/ishihara.html",
        "category"      : "Medical",
        "icon"          : "icon_ishihara",
        "visible"       : true,
        "description"   : "Randomly generated Ishihara plates for testing Red/Green color blindness. Novelty use only, not to be used as a diagnosis tool.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "LCARS Clock",
        "location"      : "lcars",
        "category"      : "Utilities",
        "icon"          : "icon_lcars",
        "visible"       : true,
        "description"   : "The LCARS clock is a simple clock and weather viewer using the Star Trek TNG LCARS aesthetic. You can read about building it on my blog.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Lights Out",
        "location"      : "lightsout",
        "category"      : "Games",
        "icon"          : "icon_lightsout",
        "visible"       : true,
        "description"   : "The standard puzzle game where you attempt to turn off all the lights by pressing buttons.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Mandley",
        "location"      : "mandelbrot/",
        "category"      : "Toys",
        "icon"          : "icon_mandley",
        "visible"       : true,
        "description"   : "A rudimentary Mandelbrot fractal explorer built using the canvas and javascript.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Manhattan",
        "location"      : "manhattan/",
        "category"      : "Demos",
        "icon"          : "icon_manhattan",
        "visible"       : true,
        "description"   : "Manhattan distance problem I developed for a coding interview!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Math",
        "location"      : "math",
        "category"      : "Utilities",
        "icon"          : "icon_math",
        "visible"       : true,
        "description"   : "Math Flashcards for Addition, Subtraction, Division, and Multiplication facts",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Maze Generator",
        "location"      : "maze",
        "category"      : "Utilities",
        "icon"          : "icon_maze",
        "visible"       : true,
        "description"   : "A small utility to create mazes of various sizes. Results can be saved as PNGs.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Miney",
        "location"      : "mines",
        "category"      : "Games",
        "icon"          : "icon_miney",
        "visible"       : true,
        "description"   : "A reinvention of the classic Minesweeper. Nothing fancy!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "N-Tris",
        "location"      : "ntris/",
        "category"      : "Games",
        "icon"          : "icon_ntris",
        "visible"       : true,
        "description"   : "Tetris clone that uses all possible shapes using up to 5 blocks.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Nomis",
        "location"      : "nomis",
        "category"      : "Games",
        "icon"          : "icon_nomis",
        "visible"       : true,
        "description"   : "You had better do what Nomis says in this classic game of repeating button presses",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Peripheral Test",
        "location"      : "medical/peripheral.html",
        "category"      : "Medical",
        "icon"          : "icon_peripheral",
        "visible"       : true,
        "description"   : "Eye test that checks for peripheral vision sensitivity. Novelty use only, not to be used as a diagnosis tool.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Pinecone Packing",
        "location"      : "pinecone",
        "category"      : "Demos",
        "icon"          : "icon_pinecone",
        "visible"       : true,
        "description"   : "Pack points the pinecone way",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Runes",
        "location"      : "runes",
        "category"      : "Utilities",
        "icon"          : "icon_runes",
        "visible"       : true,
        "description"   : "Interactive guide for solving the Phasmophobia rune puzzle",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "SIRDSy",
        "location"      : "sirdsy",
        "category"      : "Utilities",
        "icon"          : "icon_sirdsy",
        "visible"       : true,
        "description"   : "A Single Image Random Dot Stereogram (SIRDS) generator. You can make custom images by uploading black and white depth maps and textures. Results can be saved as PNGs.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Scramble",
        "location"      : "scramble",
        "category"      : "Games",
        "icon"          : "icon_scramble",
        "visible"       : true,
        "description"   : "A word game based on finding words using 9 tiles. See how many words you can find in 3 minutes!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Snakey",
        "location"      : "snake",
        "category"      : "Games",
        "icon"          : "icon_snakey",
        "visible"       : true,
        "description"   : "Reimplementation of the classic snake game using appropriated sprites in javascript.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Sorry Cards",
        "location"      : "sorry",
        "category"      : "Utilities",
        "icon"          : "icon_sorry",
        "visible"       : true,
        "description"   : "Infinite sorry cards so there is no more need to shuffle the deck 20 times per game!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Sorty",
        "location"      : "sorty",
        "category"      : "Demos",
        "icon"          : "icon_sorty",
        "visible"       : true,
        "description"   : "Demonstration that attempts to animate various methods of sorting arrays.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Speech Timer",
        "location"      : "tmtimer",
        "category"      : "Utilities",
        "icon"          : "icon_timer",
        "visible"       : true,
        "description"   : "This is a speech timer made for my local Toastmasters International club. It provides the speaker with a visual indication of when the speech should be completed.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Speed Read",
        "location"      : "speedread",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "This allows you to read text one word at a time in rapid succession. This is based off a viral vieo I saw and wanted to try it for myself.",
        "date"          : "1/29/2026",
        "tags"          : [],
        "flair"         : "BETA",
        "mobile"        : false,
    },
    {
        "name"          : "Stary",
        "location"      : "stars",
        "category"      : "Toys",
        "icon"          : "icon_stary",
        "visible"       : true,
        "description"   : "A star simulator that replicates the experience of looking out of a ship's viewport while traveling at warp speed.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Sudoku",
        "location"      : "sudoku",
        "category"      : "Utilities",
        "icon"          : "icon_sudoku",
        "visible"       : true,
        "description"   : "A Sudoku puzzle creator and solver utility.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Tunic Decoder",
        "location"      : "tunic/",
        "category"      : "Utilities",
        "icon"          : "icon_tunic",
        "visible"       : true,
        "description"   : "A simple interface for entering words from game Tunic to aid with decoding",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Word Finder",
        "location"      : "words",
        "category"      : "NYT Helpers",
        "icon"          : "icon_words",
        "visible"       : true,
        "description"   : "Find words based on given letters. Developed to help solve the Spelling Bee",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Wordy",
        "location"      : "wordy",
        "category"      : "Games",
        "icon"          : "icon_wordy",
        "visible"       : true,
        "description"   : "Wordy is a familiar puzzle game where you have to make words by connecting adjacent letters in a grid.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Ball Simulator",
        "location"      : "balls",
        "category"      : "Toys",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Ball phsyics simulation",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Binary",
        "location"      : "binary",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Simple binary converter",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Clue Sheet",
        "location"      : "clue",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Digital clue sheet for the board game, Clue",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Color Adjust",
        "location"      : "coloradjust",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Adjust the brightness and contrast of individual color channels.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Color Survey",
        "location"      : "color",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Identify colors to see where you precieve one color to start and the other to end.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Ephemidraw",
        "location"      : "draw",
        "category"      : "Toys",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Drawing, but ephemerally",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "Icony",
        "location"      : "icony/",
        "category"      : "Utilities",
        "icon"          : "icon_icony",
        "visible"       : false,
        "description"   : "Draw pixelated icons as if you are using ResEdit!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "LDS Typing Practice",
        "location"      : "typing",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Practice typing while learning cripture mastery verses",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Lightning Locator",
        "location"      : "lightninglocator",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Locate where lightning may have struck using the timing of the flash and sound.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : true,
    },
    {
        "name"          : "N^2-Tris",
        "location"      : "nntris",
        "category"      : "Games",
        "icon"          : "icon_ntris",
        "visible"       : false,
        "description"   : "Play N-Tris head-to-head locally on the same computer",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Paint Mixer",
        "location"      : "paintmixer/",
        "category"      : "Toys",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Mix CMYK paints to make new colors!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Palindrome Finder",
        "location"      : "palindrome",
        "category"      : "Demos",
        "icon"          : "icon_palindrome",
        "visible"       : true,
        "description"   : "Search a body of text for palindromes",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Pony Picker",
        "location"      : "ponies/",
        "category"      : "Toys",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Customize your own My Little Pony",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Radical",
        "location"      : "radical",
        "category"      : "Games",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Space fighting game meant to resemble the 80's game, Awesome",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Scattergories",
        "location"      : "scattergories",
        "category"      : "Games",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Simple method to play Scategories without purchasing the game!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Signal",
        "location"      : "signal",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "An attempt at creating a signal generator",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Sine",
        "location"      : "sine",
        "category"      : "Demos",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "See how a sine relates to a circle",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Strands Helper",
        "location"      : "strands/",
        "category"      : "NYT Helpers",
        "icon"          : "icon_strands",
        "visible"       : true,
        "description"   : "Get help finding words in the NYT Strands puzzle.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : "BETA",
        "mobile"        : false,
    },
    {
        "name"          : "Topic Spinner",
        "location"      : "topicspinners/",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Tool for randomly generating Table Topics for Toastmaster meetings.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },

    {
        "name"          : "3072",
        "location"      : "3072",
        "category"      : "Games",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "A game like 2048, but with hexagons!",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Angle",
        "location"      : "angle",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "A line recursively curved can form many shapes. Almost like a spirograph.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Arc",
        "location"      : "arc",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Calculate the trajectory of arcs",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Arkanoid 2 Editor",
        "location"      : "arkanoid",
        "category"      : "Utilities",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Arkanoid level editor",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Boaty",
        "location"      : "boaty",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Guide boats to their docks safely",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Bricky",
        "location"      : "bricks/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Breakout type game",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Bubbly",
        "location"      : "bubble/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Puzzle Bobble style game",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "CircleMan",
        "location"      : "circleman",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Move CircleMan around in his circular world",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "DNA",
        "location"      : "dna",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Simple model of a DNA strand",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "DecimalTime",
        "location"      : "decimaltime/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "The calendar should be made of 13 28 day months, and days should just have 10 hours. Here's what time it would be.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Etchy",
        "location"      : "etch",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Digital Etch-a-Sketch implementation",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "GameBoy",
        "location"      : "gameboy/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Gameboy emulator (someday)",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Hexdoku",
        "location"      : "hexdoku/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Sudoku using hex digits in a 16 x 16 square",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Poll",
        "location"      : "poll/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Simple polling with bars that update as you tally votes",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Pokemon Card Generator",
        "location"      : "pokemon/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Create custom pokemon cards.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Reflections",
        "location"      : "reflections",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "A study in how lines reflect",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Sirdsteroids",
        "location"      : "sirdsteroids/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "An Asteroids clone that uses SIRDs to display the game in 3D",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Sparky",
        "location"      : "sparky/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "A Qix clone",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Line-ify",
        "location"      : "lineify",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Filter to represent images by horizontal line of varying thickness",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Saw Display",
        "location"      : "saw",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Graphical display for panel saw project.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
    {
        "name"          : "Sun and Moon",
        "location"      : "sunmoon/",
        "category"      : "Ideas",
        "icon"          : "icon_missing",
        "visible"       : false,
        "description"   : "Experimental clock that shows sun and moon rises based on your location.",
        "date"          : "Unknown",
        "tags"          : [],
        "flair"         : null,
        "mobile"        : false,
    },
];

function compare(a, b){
    if (a.name < b.name)
        return -1;
    if (a.name > b.name)
        return 1;
    return 0;
}

function populate_apps(div, prefix, show_all=false){
    // Clear out div first
    div.innerHTML = "";

    apps.sort(compare);

    // Add apps by category
    for (let category of categories) {

        let category_div = document.createElement("div");
        category_div.classList.add("category");

	// Creat a heading for the category
        let category_title = document.createElement("h2");
        category_title.classList.add("category_title");
        category_title.innerHTML = category.name;
        category_div.appendChild(category_title);

        // If we have a category description, add it here
        if (category.description !="") {
            let category_description = document.createElement("p");
            category_description.innerHTML = category.description;
            category_div.appendChild(category_description);
        }

	// Add apps alphabetically
        for (let app of apps) {
            if (app.category != category.name) continue;
	    if (!show_all && app.visible == false) continue;

            let link = document.createElement("a");
            link.href = prefix+app.location;

            let div = document.createElement("div");
            div.classList.add("app")

	    let icon_wrapper = document.createElement("div");
	    icon_wrapper.classList.add("icon-wrapper");
	    if (app.flair !== null) {
		icon_wrapper.classList.add("icon-banner");
		icon_wrapper.setAttribute("data-label", app.flair);
		icon_wrapper.style = "--ribbon-color: " + flairs[app.flair];
	    }

            let icon = document.createElement("img");
            icon.classList.add("icon");
            icon.src = prefix+"icons/"+app.icon+"_256.png";

	    icon_wrapper.appendChild(icon);

            let title = document.createElement("h2");
            title.classList.add("title");
            title.innerHTML = app.name

            let description = document.createElement("p");
            description.classList.add("description");
            description.innerHTML = app.description;

            link.appendChild(icon_wrapper);
            link.appendChild(title);
            div.appendChild(link);
            div.appendChild(description);
            category_div.appendChild(div);
        }

        div.appendChild(category_div);
    }
}
